source 'https://github.com/sk409/CocoaPodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

use_frameworks!

target 'Home_Example' do
  pod 'CoreDI'
  pod 'Splash'
  pod 'Home', :path => '../'

  target 'Home_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
